### ISSUE TITLE
Collect same key twice

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#108]
In [88#discussion_r115333601](https://github.com/metarhia/MetaSync/pull/88#discussion_r115333601) @aqrln noticed that collector now increments counter even on same keys. On the one hand it's lightweight but on the other it may lead to errors in applied code. So I'd prefer to have both implementation:
- `metasync.collect(3)`
- `metasync.collect(3).distinct()`

**Comment by aqrln** [comment]
SGTM
