### ISSUE TITLE
Data collector contract

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#110]
After @aqrln proposed changes to `metasync.collect` contract here [88#discussion_r115382445](https://github.com/metarhia/MetaSync/pull/88#discussion_r115382445) I prepared following cases:
```js
const dc = metasync.collect(count).done((err, data) => {});
dc(key, value); // if 2 arguments passed
dc(key, error, value); // if 3 arguments passed

dc.pick(key, value); // on received data successfully
dc.fail(key, error); // on error

fs.readFile(filename, dc.bind(null, key)); // bind to errback contract
dc.take(key, fs.readFile, filename); // shorthand for previous
```

**Comment by tshemsedinov** [comment]
More precise:
```js
dc(key, [error], value); // error is optional
dc.pick(key, [value]); // value is optional, defaults to undefined
dc.fail(key, [error]); // error is optional, defaults to Error('Failed to collect ' + key)
dc.take(key, asyncFn, ...args); // ...args are optional
```

**Comment by aqrln** [comment]
Mostly sounds good except one thing.

```js
dc(key, [error], value); // error is optional
```

How is that going to work? Async operations normally don't pass the second argument to a callback when an error occurred, so in scenarios like

```js
fs.readFile(filename, dc.bind(null, key));
```

it'll just collect an `Error` instance as the value if the operation wasn't successful.

**Comment by tshemsedinov** [comment]
@aqrln you are right, it will be called in following cases:
- `dc(key, error);` 2 args (`key` will be bound so 1 will be passed)
- `dc(key, null, value);` 3 args (`key` will be bound so 2 will be passed)

So error shouldn't be optional or we need instanceof.

**Comment by DzyubSpirit** [comment]
@tshemsedinov @aqrln What if `take` method will be called more than `expected` times? Now it saves `expected` count values from first finished asynchronous functions. 
I think that `take` calls also must be counted and `collect` should restrict calling more times than it should be called.

**Comment by tshemsedinov** [comment]
If `pick` and `take` will be called more then expected, we should call `done` once and ignore everything after `done` (best solution will be to use `api.common.emptiness`). @belochub

**Comment by aqrln** [comment]
@tshemsedinov 

> So error shouldn't be optional or we need instanceof.

The whole point of this proposal was to avoid `instanceof`. So yes, error must not be optional. Not typing `null`s is what `dc.pick()` is for.
