### ISSUE TITLE
Can't change name of standard functions for flow syntax

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/metasync#117]
I've tried to use `metasync.flow` with `fs.readFile` function but discovered that `fs.readFile.name` is `''`. I've started hacking process. 
Hack 1:
```javascript
const fn = fs.readFile
```
`fn.name` is also `''` and can't be changed because `fn` is only reference to `fs.readFile`.
Hack 2:
```javascript
const fn = fs.readFile.bind(null);
```
`fn.name` is `'bound '` and also can't be changed.
Hack 3:
```javascript
const fn = (...args) => fs.readFile(...args);
```
`fn.name` is `'fn'` and can't be changed.
Summary: All standard and bounded functions can be used with `metasync.flow` only with Hack 3 creating new functions every time.
Is it possible to implement `metasync.flow` in different way?

**Comment by DzyubSpirit** [comment]
I've remembered that first implementations save results of asynchronous functions by 0,1.. keys. But I think it can be improved using object of functions instead of array of functions:
```javascript
metasync.flow({
  configRead: fs.readFile.bind(null, 'config.js'),
  inputRead: fs.readFile.bind(null, 'input.dat'), 
});
```
The best part is that that doesn't change much. Whole flow syntax still applicable: `{}` is sequential, `[{}]` is parallel.
The worst part is that sequential composition will be depends on key order in object.
@tshemsedinov Is it okay to start implementing `metasync.flow` in that way?

**Comment by tshemsedinov** [comment]
@DzyubSpirit where did you find such syntax `metasync.flow({ keys })` ?
We discussed only `metasync.flow([fn1, [[fn2, fn3]], fn4])(data, done => done(err, result))`
Where each function have contract with two possible cases:
- `fn(data, done) => done(err, result)`
- `fn(data, done) => { data.key = result; done(err) }`

See also #118

**Comment by tshemsedinov** [comment]
After #118 we need no `instanceof`. Function names are optional. I think it will be better to have a single data hash, accessible for all functions and assign keys in imperative style (manually) like in following code: `fn(data, done => { data.key = result; done(err) })`

**Comment by DzyubSpirit** [comment]
@tshemsedinov I didn't find such syntax, `I think it can be improved using object of functions instead of array of functions`. There I only propose a solution for original problem :)
Original problem is how to use standard and bound functions with `metasync.flow`. As I see now (after reading you suggestions) the best option is:
```javascript
const fn1 = (data, done) => fs.readFile('input.dat', (err, result) => {
  if (err) return done(err);
  data.fn1 = result;
  done(null);
});
const fn2 = (data, done) => fs.writeFile('output.dat', data.fn1, (err, result) => {
  if (err) return done(err);
  done(null);
}); 
metasync.flow([fn1, fn2]);
```
P.S. I think I really have fake memories because I've not found any evidence of that: `first implementations save results of asynchronous functions by 0,1.. keys`. Sorry about that.

**Comment by DzyubSpirit** [comment]
Using `fmap` function proposed in #121 previous code can be reduced to:
```javascript
const fn1 = (data, done) => fmap(result => (data.fn1 = result), fs.readFile('input.dat', done));
const fn2 = (data, done) => fs.writeFile('output.dat', data.fn1, done); 
metasync.flow([fn1, fn2]);
```
But I think it still can be reduced.

**Comment by DzyubSpirit** [comment]
Implementing `put` function `fn1` can be reduced to this: 
```javascript
const fn1 = (data, done) => fmap(put(data, 'fn1'), fs.readFile)('input.dat', done);
```
It's all that I can do
