### ISSUE TITLE
Functor map for asynchronous functions

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/MetaSync#121]
Common pattern for asynchronous functions is creating wrapper for callback
```javascript
const asyncFn = ...; //async function which we are working with
const args = ...; // Iterable of arguments for asyncFn
const callback = ...; // callback which we've got likely like argument from higher scope function
const f = ...; // function transforming asyncFn result
asyncFn(...args, (err, res) => {
  if (err) return callback(err);
  callback(null, f(res));
});
```
I think it's too many code for such a simple thing. It must be like this
```javascript
fmap(f, asyncFn)(callback);
```
P.S. I implemented `fmap`, `ap`, `chain` and other functions [here](https://github.com/DzyubSpirit/MetaSync/blob/async-monad/lib/monad.js#L22). But `fmap` there depends on `chain` and `of` functions. It's because of my decision to implement `chain` and `of` as basic for other functions. However if there isn't `chain` and `of` functions, `fmap` can be easily implemented

**Comment by tshemsedinov** [comment]
@DzyubSpirit make PR for `/lib/monad.js` so we will discuss code in comments

**Comment by tshemsedinov** [comment]
@DzyubSpirit see #122
