### ISSUE TITLE
Using let and const declaring loop variable

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/MetaSync#123]
As I understand our code style:
Using `let` in loops with increment:
When `i` is used in closure:
```javascript
for (let i = 0; i < len; i++) {
  () => i;
}
``` 
When `i` isn't used in closure:
```javascript
let i;
for(i = 0; i < len; i++) {
  i;
}
```
Using `const` in for..in, for..of loops:
When `i` is used in closure:
```javascript
for (const el of arr) {
  () => el;
}
```
When `i` isn't used in closure:
```javascript
let el;
for (el of arr) {
  el;
}
```
Is it right? @tshemsedinov

**Comment by tshemsedinov** [comment]
No, with closure we also declare loop variable out of loop but copy it to another closure variable.
Also we have a rule: not to declare functions in loops. Lambda as well. @DzyubSpirit

**Comment by DzyubSpirit** [comment]
@tshemsedinov 
Can we bind function in loop?

**Comment by aqrln** [comment]
@DzyubSpirit `Function.prototype.bind()` creates a new function, so I'd say no if that's not necessary. OTOH, in some rare cases creating functions inside a loop makes sense (no matter whether they are bound functions or lambdas), so use your best judgement.

**Comment by DzyubSpirit** [comment]
@aqrln  What can you say about wrapping functions which also creates functions whenever called. They also shouldn't used in loops? 
I asks because `Function.prototype.bind` and wrapping functions are hacks which bypass linter rule about lambdas in loop although the performance is the same.

**Comment by aqrln** [comment]
@DzyubSpirit I don't quite get your use case. Can please make a Gist with a sample of code so that I can provide my feedback?

Re: `Function.prototype.bind()` bypassing the linter rule: yes, that's true. If we want to be strict about not allowing function declarations inside loops, we have to forbid using `bind()` there too. I believe fiddling with `no-restricted-syntax` rule should work for that.

**Comment by DzyubSpirit** [comment]
@aqrln 
[Here](https://github.com/DzyubSpirit/MetaSync/blob/async-monad/lib/monad.js#L29) i use lambda but instead i can write function:
```javascript
const wrap = (wrappedAsyncFn, method) => (...args) => asAsync(method(wrappedAsyncFn, ...args));
```
Although that function can be declared out of loop and there would be only call to it inside loop, `wrap` creates functions.
I ask because it's hard to catch and checking for lambdas in for of bind in for doesn't help as I see.

**Comment by aqrln** [comment]
@DzyubSpirit in this specific case you create new functions on each iteration either way, and that's exactly what this piece of code is supposed to do, so just go ahead and use lambdas inside of the loop.

**Comment by tshemsedinov** [comment]
@aqrln @DzyubSpirit I'd prefer not to define functions or lambdas inside loop but call functions creating closures from the loop.
