### ISSUE TITLE
Implement .reduce(items, callback, done, initial)

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#17]
Use case:
```js
metasync.reduce(['Beijing', 'Roma', 'Kiev'], (prev, cur, callback) => {
  getCityPopulation(cur, (count) => {
    callback(prev + count);
  });
}, (err, count) => {
  console.log('Total population: ' + count);
}, 0);
```

**Comment by anxolerd** [comment]
@tshemsedinov would you kindly update the use case, so it matches the signature provided in the topic?
TIA

**Comment by aqrln** [comment]
@anxolerd doesn't it match?

**Comment by anxolerd** [comment]
@aqrln did not notice the initial and get lost in callback function =)
Sorry)

**Comment by aqrln** [comment]
@anxolerd np :)

**Comment by aqrln** [comment]
@anxolerd thanks for your feedback, though. The fact that you could not read the code snippet correctly clearly indicates that the syntax may not be that great (and it indeed isn't; things that work well in non-asynchronous world may become way too complicated when asynchronous operations are being involved). This one and accompanying functions like `metasync.filter` and `metasync.map` will surely exist mimicking `Array.prototype.*`, but we came up with an idea of much more readable and convenient alternative mechanism for applying such transformations, chainable and Promise-friendly. Stay tuned :)

**Comment by tshemsedinov** [comment]
What we certainly have... a confusing syntax )
I propose add alternative syntax:
```js
metasync.for(items).reduce(fn).done(fn);
// or
metasync.for(items).reduce(fn).then(fn).catch(fn);
```

**Comment by anxolerd** [comment]
Well, it was a surprise to find out that reduce is already implemented.
Probably the alternate chainable and promise friendly syntax should be moved to a new issue (if it does not exist), and this one should be closed in order to not confuse others...

**Comment by tshemsedinov** [comment]
See #37

**Comment by aqrln** [comment]
@anxolerd see https://github.com/metarhia/MetaSync/pull/39 and [an example of usage](https://github.com/metarhia/MetaSync/blob/c7030377f09e32598b5d87030e30ff31d0041877/chain-example.js).
