### ISSUE TITLE
Flow documentation

### ISSUE THREAD

**Issue by DzyubSpirit** [metarhia/metasync#177]
[Docs](https://github.com/DzyubSpirit/MetaSync/blob/sequential-wtih-callback-next/lib/flow.js#L8) says that `metasync.flow` returns errback function and also takes errback functions. But it confuses because these functions haven't a contract `(err, data)` but `(data, callback)` or `(callback)`

**Comment by tshemsedinov** [comment]
Each function have contract: `(par1..parN, callback) => callback(err, result)`

If we have single callback parameter `(callback) => callback(err, result)` is just an edge case.

**Comment by DzyubSpirit** [comment]
Oh sorry, I didn't explain accurately. I mean what function has errback contract? async function `(par1..parN, callback)` or callback `(err, result)`?

**Comment by tshemsedinov** [comment]
I call `errback` composition of two contracts:
- call with `last-callback` contract and 
- response with `error-first` contract

Do you know specification where those contracts and words are defined strictly? That would be great to fix terminology. @DzyubSpirit

**Comment by DzyubSpirit** [comment]
[This article](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/) says:
> The “error-first” callback (also known as an “errorback”, “errback”, or “node-style callback”) was introduced to solve this problem (standardization of callbacks), and has since become the standard for Node.js callbacks.

Looking on npm [libraries](https://www.npmjs.com/browse/keyword/errback) with keyword errback:
- **create-errback**, **stripe-errback**, **log-errback** and **fs-exists-nodeback** use errback as callback with errback contract.
- **lite-json-parse** uses errback as asynchronous function with errback callback.
I propose to use errback for callbacks with special contract and to assume that every asynchronous function has errback callback as last argument. @tshemsedinov

**Comment by tshemsedinov** [comment]
So we have no well-known terminology. Originally `errback` came from Python where it used in Deferred (Promise analogue) to return just errors (not result), so in Python `errback` is equivalent for `.catch((err) => {})`. I think it is better to use `callback-last` and `error-first` because it can't be misunderstood. @DzyubSpirit
