### ISSUE TITLE
Refactor return

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#193]
That's ok:
- `if (isDone) return;`
- `if (isDone) return this;`

Not ok:
- `if (isDone) return callback(null, data);`
- `if (isReady) return doSomething(data);`
- `return console.log('Bye');`

**Comment by aqrln** [comment]
@tshemsedinov +1. I feel like we should make an eslint rule to reinforce it.

**Comment by tshemsedinov** [comment]
After reading not my code I can agree with you @aqrln that combining return with function/method call is a bad practice, because we do not know/remember what will function return (certain type or undefined). So reading and refactoring requires reading other functions. I am going to refactor that everywhere into block:
```js
{
  doSomething(...);
  return;
}
```
if `doSomething` don't return a value. But short `return;` or `return this;` or `return instance;` (for chaining) in a single-line looks good to me.
