### ISSUE TITLE
This is the most useless lib, use link in comment

### ISSUE THREAD

**Issue by N1gma** [metarhia/metasync#236]
http://reactivex.io/rxjs/

**Comment by aqrln** [comment]
Sure, there are RxJS, Highland.js and other good, high-quality libs to help you deal with asynchrony. That's what open source is about: you are free to choose whatever suits your needs, as well as you are free to create whichever libraries you fancy, and that's particularly true about JavaScript ecosystem, where there's virtually never a single golden hammer for any kind of problem.

RxJS is awesome, but you would probably be banned from their org for violating their [Code of Conduct](https://github.com/Reactive-Extensions/RxJS/blob/master/code-of-conduct.md) if you made a similar comment there. Neither do we tolerate toxic behavior (even if this repo doesn't have an explicit code of conduct even though some of the other ones do, namely, [metarhia/jstp](https://github.com/metarhia/jstp/blob/master/CODE_OF_CONDUCT.md) and [metarhia/protocol](https://github.com/metarhia/protocol/blob/master/CODE_OF_CONDUCT.md)). You are welcome to be engaged in constructive manner, as well as you are welcome to ignore the project if you think it's useless. It's totally fine to think so — people have opinions — but mind your behavior and act with due respect. Creating objectively useless issues in subjectively "useless" repos makes neither you nor the world better, so why bother doing it? And making useless *and* snarky remarks is especially not appreciated.

Hope to see you, as a software engineer, revisit some of your core values and act according to the high standards of modern open-source community.
