### ISSUE TITLE
Implement metasync.firstOf

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#26]
```js
metasync.firstOf([f1...fN], (err, args...) => {
...
});
```
FYI: @aqrln @belochub

**Comment by DzyubSpirit** [comment]
@tshemsedinov, could you explain what that function has to do, please?

**Comment by tshemsedinov** [comment]
I think it is interesting control flow utility to catch which function returns first. It will be also `errback` compatible and need two implementations: parallel and sequential. @DzyubSpirit

**Comment by DzyubSpirit** [comment]
@tshemsedinov Could you explain how to do that function sequential? As I understand 'sequential' means second function executes after first callback has been called. It it's true then purpose of `firstOf` will be lost

**Comment by tshemsedinov** [comment]
@DzyubSpirit agree, just parallel :)
