### ISSUE TITLE
Implement metasync.timeout

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#27]
`metasync.timeout(1000, asyncFunction, doneFunction)`
FYI: @aqrln @belochub

**Comment by aqrln** [comment]
What I and @belochub needed was

```javascript
metasync.timeout(1000, asyncFunction, arg1, arg2, ..., argN, callback)
```

`callback` applies to both asyncFunction and timer, but is invoked only once, depending on what occurs first.

**Comment by tshemsedinov** [comment]
@aqrln I mean usage:
```js
metasync.timeout(1000, function() {
  asyncFunction(arg1, arg2, ..., argN);
}, doneFunction);
```

**Comment by tshemsedinov** [comment]
https://github.com/metarhia/MetaSync/commit/5fb98a17c87029f74627e027fcd1b3d9bc1a8341
https://github.com/metarhia/MetaSync/commit/c6e05686978ba0b7ac5d536cd8b954a957853681
