### ISSUE TITLE
Proposal: rebranding and functionality change

### ISSUE THREAD

**Issue by aqrln** [metarhia/MetaSync#36]
@tshemsedinov, what do you think about turning MetaSync (under some new name) into a full-blown generic library of utility functions for JavaScript with asynchronous utilities being only a part of it? We definitely need some sort of common library since I've encountered situations when two analogous functions have to be fixed twice in Impress and JSTP.

Refs: https://github.com/metarhia/Metarhia/issues/2

**Comment by tshemsedinov** [comment]
https://github.com/metarhia/Common
