### ISSUE TITLE
Refactor typeof usage for metasync

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#366]
Use `typeof valiable` instead of `typeof(variable)` except cases like this: `typeof(5 + '')`

**Comment by JuliaGerasymenko** [comment]
Sorry, but I don't have an access to push some changes into this repository and into repo metaschema.

**Comment by tshemsedinov** [comment]
Granted, @JuliaGerasymenko

**Comment by tshemsedinov** [comment]
Closed by https://github.com/metarhia/metasync/pull/369
