### ISSUE TITLE
Update to metatests 0.2.0

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#372]
Implementation @machendos
Review @lundibundi

**Comment by machendos** [comment]
https://github.com/metarhia/metasync/commit/c94fb4ed1a139ed843a5360dcb5faa688a3297ef

**Comment by nechaido** [comment]
@machendos you should open a PR and mention this issue in the PR description: "Closes: #ISSUE_CODE".

**Comment by machendos** [comment]
https://github.com/metarhia/metasync/pull/374
