### ISSUE TITLE
Bug in test/poolify-symbol

### ISSUE THREAD

**Issue by machendos** [metarhia/metasync#377]
In metatest@0.1.12 we don't require ``poolify-symbol`` test file. In 0.2.0 we require all files by ``fs.readdir()``, and tests break down due to file ``poolify-symbol``

**Comment by lundibundi** [comment]
The file doesn't test any existing functionality and we don't use any of the TDD methods here so I have removed that file in the PR (https://github.com/metarhia/metasync/pull/374/commits/05f76b1734303092513fd1c45954d3acaa53bd71).
