### ISSUE TITLE
Migrate tests/ to metatests@^0.2.1

### ISSUE THREAD

**Issue by lundibundi** [metarhia/metasync#378]
@bugagashenkj @machendos @o-rumiantsev you might be interested.

**Comment by o-rumiantsev** [comment]
Looks like @machendos has already done it in https://github.com/metarhia/metasync/pull/374

**Comment by lundibundi** [comment]
That PR doesn't touch `tests` folder.

**Comment by machendos** [comment]
Understood the task. Can I assign myself? @lundibundi

**Comment by belochub** [comment]
Closed in https://github.com/metarhia/metasync/commit/c8e5a62e5088294521b48d9893cbcc353fe67f19.
