### ISSUE TITLE
Implement AsyncArray

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#385]
Here is a task for @bugagashenkj with @belochub review
Prototyped here: https://github.com/HowProgrammingWorks/NonBlocking/blob/master/JavaScript/7-async-array.js
We may also combine this with Iterator https://github.com/metarhia/common/blob/master/lib/iterator.js
FYI: @nechaido

**Comment by bugagashenkj** [comment]
@tshemsedinov Wouldn't it be better to implement asyncMap instead of a AsyncArray?

**Comment by tshemsedinov** [comment]
We need `AsyncArray` for datasets, `AsyncMap` and `AsyncSet` for indexed collections. But it would be great if we can implement abstract `AsyncCollection` as a wrapper/boxing for all async iterable collections (supporting `Symbol.asyncIterator`). Maybe we can generate this classes dynamically with something like this: `unblock = AsyncIterableCollectionClass => NonBlockingAsyncIterableCollectionClass`

**Comment by tshemsedinov** [comment]
If you mean iterating function `asyncMap`, we need it too.

**Comment by bugagashenkj** [comment]
@belochub I think it can be closed.

**Comment by belochub** [comment]
Closed in favor of https://github.com/metarhia/metasync/issues/393.
