### ISSUE TITLE
Unused `KeyCollector` and `DataCollector`

### ISSUE THREAD

**Issue by SemenchenkoVitaliy** [metarhia/metasync#405]
It seems that `KeyCollector` and `DataCollector` from [lib/collector.prototype.js](https://github.com/metarhia/metasync/blob/master/lib/collector.prototype.js) are exported from a file but not required in [metasync.js](https://github.com/metarhia/metasync/blob/master/metasync.js) even though it is stated in [the description](https://github.com/metarhia/metasync/blob/master/metasync.js#L14).
```js
  'collector', // DataCollector and KeyCollector
```

**Comment by tshemsedinov** [comment]
We do not use this old implementation and hold it just for performance comparison and for history @SemenchenkoVitaliy
