### ISSUE TITLE
Alternative chaining syntax for collectors

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#43]
```js
const dc1 = metasync
  .collect(3)
  .timeout(5000)
  .done((err, data) => {});

dc1(item);

const dc2 = metasync
  .collect(['key1', 'key2', 'key3'])
  .timeout(5000)
  .done((err, data) => {});

dc2(key, value);
```

WDYT, @aqrln about `.timeout(number)` and firing .catch on timeout ?

**Comment by aqrln** [comment]
@tshemsedinov great. I would really like to see such Promise-compatible interfaces wherever possible especially since Node.js 7.6 now has async/await enabled without flags :)
