### ISSUE TITLE
AsyncIterator tests fails

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#441]
After dependency update #440 tests fails
See: https://travis-ci.org/metarhia/metasync/jobs/619382154
@nechaido

**Comment by lundibundi** [comment]
That is due to the way `metatests` changed the handling of tests that return Promise (and therefore `async`).
I'll push to the branch the fix.

**Comment by tshemsedinov** [comment]
https://travis-ci.org/metarhia/metasync/jobs/622009735
@lundibundi please see, is it related bug?
