### ISSUE TITLE
Callbacks in metasync.filter and metasync.find

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#50]
Now callbacks in `metasync.filter` and `metasync.find` have single argument (result or data). I think it will be good to use common convention with `(err, data)`. FYI: @aqrln

**Comment by aqrln** [comment]
Refs: https://github.com/metarhia/MetaSync/issues/12

**Comment by nechaido** [comment]
@tshemsedinov I think we can close this
