### ISSUE TITLE
Chaining optimization

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#72]
Maybe it is better to have consistent function signature in chaining.
Now in following example `fn1` and `fn2` have different signature then `fn3` and `fn4`:
```
api.metasync.for(array).filter(fn1).map(fn2).then(fn3).catch(fn4);
```
- Signature for `fn1` and `fn2` is: `(element, callback) => callback(error, result)`
- Signature for `fn3` is: `(data) => {}`
- Signature for `fn4` is: `(error) => {}`
But we can combine `.then()` and `.catch()` into `.done()`
```
api.metasync.for(array).filter(fn1).map(fn2).done(fn3);
```
Signature for `fn1` and `fn2` will be: `(element, callback) => callback(err, result)`
But here is 2 alternative syntax for `f3`:
- `(data, callback) => callback(error, data)` where result may be instance of Error or data
- `(error, data, callback) => callback(error, data)`
We need `callback` in `.done()` because chaining may contain multiple steps after `.done()`
For example:
```
api.metasync.for(array).filter(fn1).map(fn2).done(fn3).reduce(fn4).done(fn5);
```
@aqrln what do you think?

**Comment by nechaido** [comment]
@tshemsedinov I think you meant:
* Signature for fn3 is: `(data) => {}`
* Signature for fn4 is: `(error) => {}`

**Comment by tshemsedinov** [comment]
@nechaido you are right, fixed

**Comment by tshemsedinov** [comment]
Or we can implement just last `.fetch(err, data)` as in GlobalStorage Cursor, it would be consistent for all chaining functions to have `(data, callback)` and `(err, data)` signatures.
@aqrln @nechaido ?

**Comment by tshemsedinov** [comment]
Here is benchmarks: https://github.com/HowProgrammingWorks/Chaining
```
Promise.......2945622601 nanoseconds
Functor.......2652376404 nanoseconds
Prototype......984661658 nanoseconds
```

**Comment by aqrln** [comment]
Node.js 8:

```
Promise.......1931976515 nanoseconds
Functor.......2557655192 nanoseconds
Prototype......954325494 nanoseconds
```

Those sweet Promise optimizations in V8 5.7 :)
Not sure about 5.7 though, but AFAIK native promises in the latest V8 are even faster than `bluebird`.

**Comment by tshemsedinov** [comment]
That's great, but I think we can hold this test for future refactoring and use prototypes. Yes, it's largest, not so beautiful and not so clear implementation but it's not for subject domain logic, it's just for library internal thing, so we need to use fastest. @aqrln

**Comment by tshemsedinov** [comment]
Here is benchmarks changes after double iterations. Alo tested on `node@7.8.0` and `v8@5.5.372.43`
```
Promise......10842458400 nanoseconds
Functor.......6316806103 nanoseconds
Prototype.....2079794829 nanoseconds
ProtoBuild....2089720294 nanoseconds
```
I added prototype dynamic building with mixins and closure, It not much slower, but but also not so clear, so I'd prefer not building prototype dynamically here.
@aqrln @nechaido

**Comment by tshemsedinov** [comment]
@aqrln @nechaido need your feedback about [#issuecomment-292656097](https://github.com/metarhia/MetaSync/issues/72#issuecomment-292656097)

We have chosen prototypes/callbacks implementation, so we are not promise-compatible. It would be better to be compatible with common Node.js async I/O style and not confusing anybody with then/fetch.

I would like to have:
`metasync.for(data).map((item, cb) => cb(err, result)).fetch((err, data) => {})`
instead of
`metasync.for(data).map((item, cb) => cb(err, result)).then((data) => {}).catch((err) => {})`

**Comment by aqrln** [comment]
@tshemsedinov yup, +1 on it. Mimicking Promise contract is misleading when Promises cannot be, e.g., returned from callbacks passed to the methods of `ArrayChain`, nor it is logical or consistent to use a different contract for methods used to retrieve the result than for ones used in the interim computations. So let's stick to that `fetch` method.
