### ISSUE TITLE
Dynamically build ArrayChain.prototype

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#73]
`['then', 'catch', 'map', 'filter', 'reduce', 'each', 'series', 'find']` on library load

**Comment by tshemsedinov** [comment]
See implementation [HowProgrammingWorks/Chaining/JavaScript/3-prototype-build.js](here https://github.com/HowProgrammingWorks/Chaining/blob/master/JavaScript/3-prototype-build.js) and performance results comparison here: https://github.com/metarhia/MetaSync/issues/72 so I have doubts whether we should do this.

**Comment by nechaido** [comment]
I think that there is no point in doing this
