### ISSUE TITLE
Move metasync.cb to common.cb

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#74]
This wrapper needed even inside `common` so to avoid recursive dependency is will be good to move it from `metasync.cb` to `common.cb`. Mark `metasync.cb` as deprecated and support it in `metasync@0.2.x`. We will remove support in `metasync@0.3`.

**Comment by nechaido** [comment]
@tshemsedinov I think we can close this

**Comment by tshemsedinov** [comment]
Landed in d18dab4c4d936aa84805f1ae17d57845e764adf5
