### ISSUE TITLE
Failing tests should exit loudly

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/metasync#79]
Now tests silently failing, #77

**Comment by nechaido** [comment]
@tshemsedinov I propose we use [tap](http://www.node-tap.org/basics/) for testing, it works well with asynchronous functions.

**Comment by aqrln** [comment]
@nechaido yeah, I've used `tap` and so far I like it the most among the existing testing frameworks. It has an extensive feature set (including testing asynchronous code like a charm, analyzing code coverage and virtually anything else you might need) yet maintaining simple and minimalistic API.

**Comment by tshemsedinov** [comment]
@nechaido @aqrln ok, we can try
@nechaido please prepare tap test for `metasync.find()` and `metasync.for().map()`

**Comment by nechaido** [comment]
@tshemsedinov @aqrln here are examples of tests using:
* [mocha](https://github.com/metarhia/MetaSync/tree/test-mocha/test)
* [tap](https://github.com/metarhia/MetaSync/tree/tests/test)

**Comment by nechaido** [comment]
@tshemsedinov @aqrln here is one more alternative this time using [jest](https://github.com/metarhia/MetaSync/tree/test-jest/test)

**Comment by aqrln** [comment]
@nechaido I can see a few issues in your tests. Can you please raise PRs for them so that we can start the reviewing process right away? Opening and closing PRs is cheap, that's okay to land only one of them ;)
