### ISSUE TITLE
Broken metasync.find 

### ISSUE THREAD

**Issue by tshemsedinov** [metarhia/MetaSync#82]
We have totally broken `metasync.find`, I tested it writing chaining test

**Comment by nechaido** [comment]
@tshemsedinov what is the problem? Does https://github.com/metarhia/MetaSync/pull/75 fix it?

**Comment by tshemsedinov** [comment]
See test retults: https://github.com/metarhia/MetaSync/commit/a9836b92b9479b3a3506c49f1b79f8189b0a393a

**Comment by tshemsedinov** [comment]
https://travis-ci.org/metarhia/MetaSync/jobs/222055726
